// Keep GitHub links only for repositories verified as public.
const projects = [
  { name: '360 to MP4', category: 'Personal tools', description: 'A pipeline for converting GoPro .360 footage to stitched equirectangular MP4, staging through local disk to work around GoPro Player.' },
  { name: 'ShrineSim', category: 'Games', description: 'A simulation project centred on the rhythm and operations of a shrine.', github: 'https://github.com/hayhayh/ShrineSim' },
  { name: 'Actor MCP Server', category: 'AI tools', description: 'A local checkout of Apify’s Model Context Protocol server for working with Actors.', github: 'https://github.com/apify/apify-mcp-server' },
  { name: 'Apply Job Agent', category: 'Career', description: 'Automation experiments for finding and applying to suitable roles.' },
  { name: 'Artsy Fartsy Event Manager', category: 'Culture', description: 'A small event-management tool that gathers events from Instagram, Meetup, and WhatsApp.' },
  { name: 'Article Summarisation Extension (archive)', category: 'Browser', description: 'An archived earlier version of the article-summarising browser extension.' },
  { name: 'Auto Apply Jobs', category: 'Career', description: 'A job-scraping and application-tracking workflow.' },
  { name: 'Board Game Auction Analysis', category: 'Data', description: 'Data analysis tools for board-game auction lists and BoardGameGeek statistics.' },
  { name: 'Bypass Paywalls', category: 'Browser', description: 'A local checkout of a browser extension for reader-side paywall handling.' },
  { name: 'Career Ops', category: 'Career', description: 'A local checkout of a structured toolkit for managing a career search.', github: 'https://github.com/santifer/career-ops' },
  { name: 'Carousell Board Game Scanner', category: 'Data', description: 'A scanner for finding and evaluating board-game listings on Carousell.' },
  { name: 'CC Spending Tracker', category: 'Personal tools', description: 'A personal tool for keeping an eye on credit-card spending.' },
  { name: 'Claude SEO', category: 'AI tools', description: 'A local checkout of an AI-assisted SEO workflow and its extensions.', github: 'https://github.com/AgriciDaniel/claude-seo' },
  { name: 'Computer Use Preview', category: 'AI tools', description: 'A local checkout of Google’s computer-use preview examples.', github: 'https://github.com/google-gemini/computer-use-preview' },
  { name: 'PDF to EPUB Converter', category: 'AI tools', description: 'An OCR pipeline that turns scanned PDFs into proofread EPUBs by reconciling output from multiple vision models.' },
  { name: 'Cron Calendar Update', category: 'Automation', description: 'Scheduled tooling for parsing events and keeping a calendar current.' },
  { name: 'Events Newsletter Parser', category: 'Culture', description: 'Parses event newsletters into structured, usable event data.' },
  { name: 'Fill Arrival Cards', category: 'Travel', description: 'A helper for preparing arrival-card details and forms.' },
  { name: 'Fuji Rock Accommodation Checker', category: 'Travel', description: 'Checks accommodation options for a Fuji Rock trip.' },
  { name: 'Gen Slides', category: 'AI tools', description: 'Experiments in programmatically generating presentations.' },
  { name: 'Holmes', category: 'AI tools', description: 'A local workspace for the Holmes project and its supporting tools.' },
  { name: 'Indian Racer', category: 'Games', description: 'A browser game prototype with Mumbai street ambience.' },
  { name: 'Job Hunt', category: 'Career', description: 'Personal tools and notes for organising a job search.' },
  { name: 'Learn German', category: 'Learning', description: 'A personal project for practising and organising German study.' },
  { name: 'LinkedIn Unwrapped', category: 'Data', description: 'A visual summary tool for exploring personal LinkedIn activity and statistics.' },
  { name: 'Mahjong MCR Trainer', category: 'Games', description: 'Learning materials and an app for training at Mahjong Competition Rules.' },
  { name: 'MCR Mahjong', category: 'Games', description: 'A multiplayer Mahjong Competition Rules game with scoring and AI support.', github: 'https://github.com/hayhayh/mcr-mahjong' },
  { name: 'Mekong Scraper', category: 'Data', description: 'A purpose-built scraper for collecting Mekong-related content.' },
  { name: 'Museum OCR', category: 'Culture', description: 'Experiments in extracting text and metadata from museum materials.' },
  { name: 'Music Link Scraper', category: 'Data', description: 'A utility for gathering music links from the web.' },
  { name: 'Article Summarisation Extension', category: 'Browser', description: 'A cross-browser extension that summarises articles while you read.' },
  { name: 'My E-reader', category: 'Personal tools', description: 'A personal e-reader application with separate frontend and backend.' },
  { name: 'My LLM Wiki', category: 'AI tools', description: 'A personal knowledge base for organising LLM-related notes and resources.' },
  { name: 'Nanobot', category: 'AI tools', description: 'A local checkout of the Nanobot personal AI assistant project.', github: 'https://github.com/HKUDS/nanobot' },
  { name: 'Ollama Deep Researcher', category: 'AI tools', description: 'A local checkout of a local-model deep-research assistant.', github: 'https://github.com/langchain-ai/local-deep-researcher' },
  { name: 'OpenCode VPS', category: 'AI tools', description: 'Spec and runbook for running an OpenCode server on a VPS, reachable only over Tailscale and behind a password.' },
  { name: 'Pocket Clone', category: 'Personal tools', description: 'A read-it-later product experiment spanning mobile, frontend, backend, and extension clients.' },
  { name: 'Record Google Meet Extension', category: 'Browser', description: 'A browser extension for recording web-conference sessions.' },
  { name: 'Rehearsal Trainer', category: 'Learning', description: 'A practice tool for rehearsing and improving performance or presentation delivery.' },
  { name: 'Rehearsal Trainer Redesign', category: 'Learning', description: 'A redesign exploration for the rehearsal-training experience.' },
  { name: 'Sandcastle Tiered Orchestrator', category: 'AI tools', description: 'An early-stage orchestrator for routing AI work through sandboxed, tiered execution.', github: 'https://github.com/hayhayh/sandcastle-tiered-orchestrator' },
  { name: 'Baybeats Scraper', category: 'Culture', description: 'A scraper for the Baybeats music festival line-up, with rendered schedule images and a WhatsApp digest.' },
  { name: 'CC Deals Scraper', category: 'Data', description: 'A web scraper for collecting and presenting Credit Card deal information.' },
  { name: 'Chinese Author Events Scraper', category: 'Culture', description: 'Collects event information for Chinese authors.' },
  { name: 'GTLF 2025 Scraper', category: 'Culture', description: 'A project for collecting programme information from a literature festival.' },
  { name: 'GTF Scraper', category: 'Culture', description: 'A parser and scraper for literary-event information.' },
  { name: 'Hotels Fuji Rock Scraper', category: 'Travel', description: 'Collects hotel availability and pricing data for Fuji Rock planning.' },
  { name: 'Jaipur Literature Festival Scraper', category: 'Culture', description: 'Collects programme and event information from Jaipur Literature Festival.' },
  { name: 'SIWF Scraper', category: 'Culture', description: 'Scrapes the Seoul International Writers’ Festival programme into a single CSV, one row per programme with detail-page descriptions.', github: 'https://github.com/hayhayh/scrape_siwf' },
  { name: 'UWRF Scraper', category: 'Culture', description: 'Scrapes the Ubud Writers & Readers Festival programme into an annotatable event store, on a scheduled run.' },
  { name: 'Substack Scraper', category: 'Data', description: 'A utility for collecting data from Substack publications.' },
  { name: 'Transcribe Meeting Events', category: 'AI tools', description: 'Transcribes meeting recordings and turns them into structured event information.' },
  { name: 'Ubud 2025', category: 'Travel', description: 'Planning materials and tools for an Ubud trip.' },
  { name: 'VC Digest', category: 'Data', description: 'A digest workflow for collecting and processing venture-capital updates.' },
  { name: 'Website Summarizer Plugin', category: 'Browser', description: 'A browser plugin for creating concise summaries of websites.' },
  { name: 'Whisper.cpp', category: 'AI tools', description: 'A local checkout of the high-performance Whisper inference project.', github: 'https://github.com/ggml-org/whisper.cpp' },
  { name: 'YouTube Enhancer', category: 'Browser', description: 'A browser extension for improving the YouTube viewing experience.', github: 'https://github.com/hayhayh/youtube-enhancer-plugin' },
  { name: 'YouTube History', category: 'Data', description: 'Scripts and datasets for exploring YouTube watch and search history.' }
];
